CREATE TABLE TABLEA (Id int)
CREATE TABLE TABLEB (Id int)


INSERT INTO TABLEA VALUES(1),(1),(2),(NULL)

INSERT INTO TABLEB VALUES(1),(2),(NULL)


SELECT * FROM TABLEA
SELECT * FROM TABLEB


SELECT * FROM TABLEA A JOIN TABLEB B ON A.Id = B.Id

SELECT * FROM TABLEA A LEFT JOIN TABLEB B ON A.Id = B.Id

SELECT * FROM TABLEA A RIGHT JOIN TABLEB B ON A.Id = B.Id

SELECT * FROM TABLEA A FULL OUTER JOIN TABLEB B ON A.Id = B.Id

SELECT * FROM TABLEA  CROSS JOIN TABLEB 