

SELECT DATEADD(YEAR,1,GETDATE())

SELECT DATEADD(MM,1,GETDATE())

SELECT DATEADD(YEAR,-3,GETDATE())

SELECT DATEDIFF(YEAR,DATEFROMPARTS(2010,1,1),GETDATE())

SELECT DATEDIFF(MM,DATEFROMPARTS(2010,1,1),GETDATE())

SELECT DATEDIFF(DD,DATEFROMPARTS(2010,1,1),GETDATE())

SELECT EOMONTH(GETDATE(),0)

SELECT EOMONTH(GETDATE(),1)

SELECT EOMONTH(GETDATE(),-1)