SELECT * FROM EMPLOYEES

ALTER TABLE EMPLOYEES
ADD Email varchar(100)

ALTER TABLE EMPLOYEES
ADD Phone varchar(20), city varchar(20)

ALTER TABLE EMPLOYEES
DROP COLUMN Email

ALTER TABLE EMPLOYEES
DROP COLUMN Phone,city


ALTER TABLE EMPLOYEES
ALTER COLUMN EmployeeName varchar(200)