

SELECT TOP 10 * FROM DimProduct

SELECT * FROM DimProduct
ORDER BY ProductKey
OFFSET 10 ROWS

SELECT * FROM DimProduct
ORDER BY ProductKey
OFFSET 10 ROWS
FETCH FIRST 10 ROWS ONLY

SELECT * FROM DimProduct
ORDER BY ProductKey
OFFSET 10 ROWS
FETCH NEXT 10 ROWS ONLY