SELECT FULLNAME FROM EMPLOYEESBK


SELECT FULLNAME ,
LEFT(FULLNAME,3)
FROM EMPLOYEESBK

SELECT FULLNAME,LEFT(FULLNAME,CHARINDEX(' ',FULLNAME)) Firstname
FROM EMPLOYEESBK

SELECT FULLNAME,TRIM(LEFT(FULLNAME,CHARINDEX(' ',FULLNAME)))
Firstname
FROM EMPLOYEESBK

SELECT FULLNAME,LEFT(FULLNAME,CHARINDEX(' ',FULLNAME)-1) Firstname
FROM EMPLOYEESBK

SELECT FULLNAME,RIGHT(FULLNAME,
LEN(FULLNAME)-CHARINDEX(' ',FULLNAME,CHARINDEX(' ',FULLNAME)+1)) LastName
FROM EMPLOYEESBK

SELECT CHARINDEX(


SELECT FULLNAME,LEFT(FULLNAME,CHARINDEX(' ',FULLNAME)-1) Firstname,
RIGHT(FULLNAME,
LEN(FULLNAME)-CHARINDEX(' ',FULLNAME,CHARINDEX(' ',FULLNAME)+1)) LastName
FROM EMPLOYEESBK