

SELECT YEAR(DATEFROMPARTS(2021,12,26))

SELECT YEAR(GETDATE())

SELECT BirthDate, YEAR(BirthDate) FROM DimEmployee


SELECT MONTH(GETDATE())

SELECT BirthDate, MONTH(BirthDate) FROM DimEmployee

SELECT DAY(GETDATE())

SELECT BirthDate, DAY(BirthDate) FROM DimEmployee

SELECT DATEPART(YYYY,GETDATE())

SELECT DATEPART(MM,GETDATE())

SELECT DATEPART(DD,GETDATE())

SELECT DATEPART(WEEKDAY,GETDATE())

SELECT DATENAME(YYYY,GETDATE())

SELECT DATENAME(MM,GETDATE())


SELECT DATENAME(WEEKDAY,GETDATE())

SELECT FORMAT(GETDATE(),'yy')

SELECT FORMAT(GETDATE(),'yyyy')

SELECT FORMAT(GETDATE(),'dd')
SELECT FORMAT(GETDATE(),'ddd')

SELECT FORMAT(GETDATE(),'MM')

SELECT FORMAT(GETDATE(),'MMM')

SELECT FORMAT(GETDATE(),'MMMM')


SELECT FORMAT(GETDATE(),'hh')

SELECT FORMAT(GETDATE(),'mm')

SELECT FORMAT(GETDATE(),'dd-MMM-yyy hh:mm:ss')

