SELECT * into PivotData FROM(
SELECT CITY,DEPARTMENT,Salary FROM EMPLOYEES)T
PIVOT(SUM(Salary) FOR DEPARTMENT IN(IT,Sales))P

SELECT * FROM PivotData

SELECT CITY,DEPARTMENT,Salary FROM(
SELECT CITY,IT,SALES FROM PivotData)T
UNPIVOT(Salary FOR DEPARTMENT IN(IT,Sales))U