-- check the existing triggers 
-- SELECT 
-- 	s.name as schemaname,
-- 	tbl.name as tablename,
--     t.name AS TriggerName,
--     te.type_desc AS TriggerEvent
-- FROM sys.triggers t
-- JOIN sys.trigger_events te ON t.object_id = te.object_id
-- JOIN sys.tables tbl ON t.parent_id = tbl.object_id
-- JOIN sys.schemas s ON tbl.schema_id = s.schema_id
-- WHERE tbl.name in ('Customer','Person','PersonPhone','EmailAddress','AddressType','BusinessEntityAddress',
-- 'Address','Employee','Department','EmployeeDepartmentHistory','Product','ProductModel','ProductCategory',
-- 'ProductSubcategory','BusinessEntity');

-- Drop existing triggers if any

-- create triggers as needed
-- Person.Address
-- IF OBJECT_ID('Person.Address_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Person.Address_UpdateTrigger;
-- GO
-- CREATE TRIGGER Person.Address_UpdateTrigger
-- ON Person.Address
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Person.Address t
--     INNER JOIN inserted i ON t.AddressID = i.AddressID;
-- END;
-- GO

-- -- Person.person
-- IF OBJECT_ID('Person.Person_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Person.Person_UpdateTrigger;   
--     GO
-- CREATE TRIGGER Person.Person_UpdateTrigger
-- ON Person.Person
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Person.Person t
--     INNER JOIN inserted i ON t.BusinessEntityID = i.BusinessEntityID;
-- END;
-- GO

-- -- Person.PersonPhone
-- IF OBJECT_ID('Person.PersonPhone_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Person.PersonPhone_UpdateTrigger;   
--     GO
-- CREATE TRIGGER Person.PersonPhone_UpdateTrigger
-- ON Person.PersonPhone
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Person.PersonPhone t
--     INNER JOIN inserted i ON t.BusinessEntityID = i.BusinessEntityID 
--                           AND t.PhoneNumber = i.PhoneNumber 
--                           AND t.PhoneNumberTypeID = i.PhoneNumberTypeID;
-- END;
-- GO

-- -- Person.AddressType
-- IF OBJECT_ID('Person.AddressType_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Person.AddressType_UpdateTrigger;
-- GO
-- CREATE TRIGGER Person.AddressType_UpdateTrigger
-- ON Person.AddressType
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Person.AddressType t
--     INNER JOIN inserted i ON t.AddressTypeID = i.AddressTypeID;
-- END;
-- GO

-- -- Person.BusinessEntity
-- IF OBJECT_ID('Person.BusinessEntity_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Person.BusinessEntity_UpdateTrigger;
-- GO
-- CREATE TRIGGER Person.BusinessEntity_UpdateTrigger
-- ON Person.BusinessEntity
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Person.BusinessEntity t
--     INNER JOIN inserted i ON t.BusinessEntityID = i.BusinessEntityID;
-- END;
-- GO

-- -- Person.BusinessEntityAddress (composite PK)
-- IF OBJECT_ID('Person.BusinessEntityAddress_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Person.BusinessEntityAddress_UpdateTrigger;
-- GO
-- CREATE TRIGGER Person.BusinessEntityAddress_UpdateTrigger
-- ON Person.BusinessEntityAddress
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Person.BusinessEntityAddress t
--     INNER JOIN inserted i 
--         ON t.BusinessEntityID = i.BusinessEntityID
--        AND t.AddressID = i.AddressID
--        AND t.AddressTypeID = i.AddressTypeID;
-- END;
-- GO

-- -- Sales.Customer
-- IF OBJECT_ID('Sales.Customer_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Sales.Customer_UpdateTrigger;
-- GO
-- CREATE TRIGGER Sales.Customer_UpdateTrigger
-- ON Sales.Customer
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Sales.Customer t
--     INNER JOIN inserted i ON t.CustomerID = i.CustomerID;
-- END;
-- GO

-- -- HumanResources.Department
-- IF OBJECT_ID('HumanResources.Department_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER HumanResources.Department_UpdateTrigger;
-- GO
-- CREATE TRIGGER HumanResources.Department_UpdateTrigger
-- ON HumanResources.Department
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM HumanResources.Department t
--     INNER JOIN inserted i ON t.DepartmentID = i.DepartmentID;
-- END;
-- GO

-- -- Person.EmailAddress (composite PK)
-- IF OBJECT_ID('Person.EmailAddress_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Person.EmailAddress_UpdateTrigger;
-- GO
-- CREATE TRIGGER Person.EmailAddress_UpdateTrigger
-- ON Person.EmailAddress
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Person.EmailAddress t
--     INNER JOIN inserted i 
--         ON t.BusinessEntityID = i.BusinessEntityID
--        AND t.EmailAddressID = i.EmailAddressID;
-- END;
-- GO

-- -- HumanResources.Employee
-- IF OBJECT_ID('HumanResources.Employee_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER HumanResources.Employee_UpdateTrigger;
-- GO
-- CREATE TRIGGER HumanResources.Employee_UpdateTrigger
-- ON HumanResources.Employee
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM HumanResources.Employee t
--     INNER JOIN inserted i ON t.BusinessEntityID = i.BusinessEntityID;
-- END;
-- GO

-- -- HumanResources.EmployeeDepartmentHistory (composite PK)
-- IF OBJECT_ID('HumanResources.EmployeeDepartmentHistory_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER HumanResources.EmployeeDepartmentHistory_UpdateTrigger;
-- GO
-- CREATE TRIGGER HumanResources.EmployeeDepartmentHistory_UpdateTrigger
-- ON HumanResources.EmployeeDepartmentHistory
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM HumanResources.EmployeeDepartmentHistory t
--     INNER JOIN inserted i 
--         ON t.BusinessEntityID = i.BusinessEntityID
--        AND t.DepartmentID = i.DepartmentID
--        AND t.ShiftID = i.ShiftID
--        AND t.StartDate = i.StartDate;
-- END;
-- GO

-- -- Production.Product
-- IF OBJECT_ID('Production.Product_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Production.Product_UpdateTrigger;
-- GO
-- CREATE TRIGGER Production.Product_UpdateTrigger
-- ON Production.Product
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Production.Product t
--     INNER JOIN inserted i ON t.ProductID = i.ProductID;
-- END;
-- GO

-- -- Production.ProductModel
-- IF OBJECT_ID('Production.ProductModel_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Production.ProductModel_UpdateTrigger;
-- GO
-- CREATE TRIGGER Production.ProductModel_UpdateTrigger
-- ON Production.ProductModel
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Production.ProductModel t
--     INNER JOIN inserted i ON t.ProductModelID = i.ProductModelID;
-- END;
-- GO

-- -- Production.ProductCategory
-- IF OBJECT_ID('Production.ProductCategory_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Production.ProductCategory_UpdateTrigger;
-- GO
-- CREATE TRIGGER Production.ProductCategory_UpdateTrigger
-- ON Production.ProductCategory
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Production.ProductCategory t
--     INNER JOIN inserted i ON t.ProductCategoryID = i.ProductCategoryID;
-- END;
-- GO

-- -- Production.ProductSubcategory
-- IF OBJECT_ID('Production.ProductSubcategory_UpdateTrigger') IS NOT NULL
--     DROP TRIGGER Production.ProductSubcategory_UpdateTrigger;
-- GO
-- CREATE TRIGGER Production.ProductSubcategory_UpdateTrigger
-- ON Production.ProductSubcategory
-- AFTER UPDATE
-- AS
-- BEGIN
--     SET NOCOUNT ON;
--     UPDATE t SET ModifiedDate = GETDATE()
--     FROM Production.ProductSubcategory t
--     INNER JOIN inserted i ON t.ProductSubcategoryID = i.ProductSubcategoryID;
-- END;
-- GO