CREATE TABLE EMPLOYEES(
    EMPID INT PRIMARY KEY,
    EMPNAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2)
);
ALTER TABLE EMPLOYEES ADD EMAIL VARCHAR(50);
INSERT INTO EMPLOYEES(EMPID,EMPNAME,DEPARTMENT,SALARY,EMAIL)
VALUES(1,'SHRAVYA','IT',75000,'shravya@gmail.com'),
(2,'ammu','cse',50000,'ammu@gmail.com'),
(3,'balu','ece',40000,'balu@gmail.com');
SELECT *FROM EMPLOYEES
CREATE TABLE EMPLOYEES_INFO(
    EMPID INT PRIMARY KEY,
    EMPNAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2)
);
ALTER TABLE EMPLOYEES_INFO ADD EMAIL VARCHAR(50);
INSERT INTO EMPLOYEES_INFO(EMPID,EMPNAME,DEPARTMENT,SALARY,EMAIL)
VALUES(4,'PINKY','IT',75000,'pinky@gmail.com'),
(2,'ammu','cse',50000,'ammu@gmail.com');
SELECT *FROM EMPLOYEES_INFO

MERGE EMPLOYEES AS TARGET
USING EMPLOYEES_INFO AS SOURCE
ON TARGET.EMPID = SOURCE.EMPID
WHEN MATCHED THEN
    UPDATE SET TARGET.SALARY = SOURCE.SALARY,
               TARGET.DEPARTMENT = SOURCE.DEPARTMENT
WHEN NOT MATCHED THEN
    INSERT (EMPID, EMPNAME, DEPARTMENT, SALARY)
    VALUES (SOURCE.EMPID, SOURCE.EMPNAME, SOURCE.DEPARTMENT, SOURCE.SALARY);
 SELECT *FROM EMPLOYEES   

