CREATE Table EMPLOYEEDETAIL(
    EMPID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    JOININGDATE DATE,
    DEPARTMENT VARCHAR(50),
    GENDER VARCHAR(50)
);
INSERT INTO EMPLOYEEDETAIL VALUES
(1,'JOE','MARIE',50000,'1-2-2020','IT','MALE'),
(2,'ABBAS','RAJ',45000,'2-3-2021','CSE','MALE'),
(3,'ABHI','RAM',60000,'6-7-2025','MECH','MALE'),
(4,'SRI','PRIYA',60000,'7-8-2025','ECE','FEMALE');
SELECT *FROM EMPLOYEEDETAIL
SELECT FIRSTNAME FROM EMPLOYEEDETAIL
SELECT UPPER (FIRSTNAME)  AS [FIRSTNAME ]FROM EMPLOYEEDETAIL
SELECT LOWER (FIRSTNAME)  AS [FIRSTNAME ]FROM EMPLOYEEDETAIL
SELECT FIRSTNAME +''+ LASTNAME AS [NAME] FROM EMPLOYEEDETAIL
SELECT *FROM EMPLOYEEDETAIL WHERE FIRSTNAME = 'RAM'
SELECT *FROM EMPLOYEEDETAIL WHERE FIRSTNAME LIKE 'a%'
SELECT *FROM EMPLOYEEDETAIL WHERE FIRSTNAME LIKE '%R%'
SELECT *FROM EMPLOYEEDETAIL WHERE FIRSTNAME LIKE '%I'
SELECT *FROM EMPLOYEEDETAIL WHERE FIRSTNAME LIKE '[A-P]%'
SELECT *FROM EMPLOYEEDETAIL WHERE FIRSTNAME LIKE '[^A-P]%'


